<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Size extends Model
{
    protected $fillable = ['size'];

    public function items() {
        return $this->belongsToMany('App\Models\Size');
    }

    public function toArray()
    {
//        return parent::toArray(); // TODO: Change the autogenerated stub
        return $this->id;
    }
}
